/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/untitled.glb -o C:\Users\91827\Desktop\portfolio\vite-project\src\assets\components\Avatar.jsx -k -r public 
*/

import React from 'react'
import { useGraph, useFrame, useThree } from '@react-three/fiber'
import { useGLTF, useAnimations, useFBX } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect, useState ,useRef} from 'react'
import * as THREE from 'three'
 
export function Model(props) {
  const { isMobile } = props; // Accept isMobile prop
  
  const { scene }= useGLTF('/model/untitled.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
   
  const {animations:walkinganimation} =useFBX('/animation/Walking.fbx')
  const {animations:idle} =useFBX('/animation/idle.fbx')
  const {animations:falldeath} =useFBX('/animation/Standing React Death Right.fbx')
  idle[0].name = "Idle";
  walkinganimation[0].name = "Walking";
  falldeath[0].name = "falldeath";
  console.log(falldeath)
  const group = useRef();
  const { actions } = useAnimations(
    [idle[0], walkinganimation[0], falldeath[0]],
    group
  );
  const [animation, setAnimation] = useState("Idle");
  const [rotationY, setRotationY] = useState(0);
  const [modelPosition, setModelPosition] = useState([0, 0, 0]);
  const [isAutoWalking, setIsAutoWalking] = useState(false);
  const [autoWalkTarget, setAutoWalkTarget] = useState(null);
  const [autoWalkDirection, setAutoWalkDirection] = useState(null);
  const { camera } = useThree();
  const initialCameraPosition = React.useRef(null);
  const targetCameraPosition = React.useRef(new THREE.Vector3());
  const lastModelPosition = React.useRef(new THREE.Vector3());
  const cameraOffset = React.useRef(null); // Store the initial offset

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.repeat) return; // Prevent auto-repeat
      handleMovement(e.key.toLowerCase(), true);
    };

    const handleKeyUp = (e) => {
      handleMovement(e.key.toLowerCase(), false);
    };

    // Handle virtual control events
    const handleCharacterMove = (event) => {
      const { key, isPressed } = event.detail;
      handleMovement(key, isPressed);
    };

    // Handle navigation events
    const handleNavigateToSection = (event) => {
      const { position } = event.detail;
      
      if (!group.current) return;
      
      const targetZ = position;
      const currentZ = group.current.position.z;
      
      console.log(`Navigation triggered: Current Z=${currentZ}, Target Z=${targetZ}`);
      
      // Don't start auto walk if already at target
      if (Math.abs(targetZ - currentZ) < 0.5) {
        console.log("Already at target position");
        return;
      }
      
      // Set up automatic walking to target
      setAutoWalkTarget(targetZ);
      setIsAutoWalking(true);
      
      if (targetZ > currentZ) {
        // Need to go forward (like pressing W)
        console.log("Walking forward to target");
        setAutoWalkDirection("forward");
        setAnimation("Walking");
        setRotationY(0);
      } else {
        // Need to go backward (like pressing S)
        console.log("Walking backward to target");
        setAutoWalkDirection("backward");
        setAnimation("Walking");
        setRotationY(Math.PI);
      }
    };

    const handleMovement = (key, isPressed) => {
      // Prevent manual movement during auto-walking
      if (isAutoWalking) return;
      
      if (key === "w" || key === "arrowup") {
        if (isPressed) {
          // Prevent walking forward if at or beyond z=60
          if (group.current && group.current.position.z >= 60) {
            setAnimation("falldeath");
            return;
          }
          setAnimation("Walking");
          setRotationY(0);
        } else {
          setAnimation("Idle");
        }
      }
      if (key === "s" || key === "arrowdown") {
        if (isPressed) {
          // Prevent walking backward if at or below z=-20
          if (group.current && group.current.position.z <= -10) {
            setAnimation("falldeath");
            return;
          }
          setRotationY(Math.PI);
          setAnimation("Walking");
        } else {
          setRotationY(0);
          setAnimation("Idle");
        }
      }
      if (key === "a") {
        if (isPressed) {
          // Prevent walking left if at or beyond x=-9
          if (group.current && group.current.position.x <= -7) {
            setAnimation("falldeath");
            return;
          }
          setRotationY(-Math.PI / 2);
          setAnimation("Walking");
        } else {
          setAnimation("Idle");
        }
      }
      if (key === "d") {
        if (isPressed) {
          // Prevent walking right if at or beyond x=9
          if (group.current && group.current.position.x >= 7) {
            setAnimation("falldeath");
            return;
          }
          setRotationY(Math.PI / 2);
          setAnimation("Walking");
        } else {
          setAnimation("Idle");
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    window.addEventListener('characterMove', handleCharacterMove);
    window.addEventListener('navigateToSection', handleNavigateToSection);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
      window.removeEventListener('characterMove', handleCharacterMove);
      window.removeEventListener('navigateToSection', handleNavigateToSection);
    };
  }, [isAutoWalking]); // Add isAutoWalking as dependency

  useEffect(() => {
    if (!initialCameraPosition.current) {
      initialCameraPosition.current = camera.position.clone();
      targetCameraPosition.current.copy(camera.position);
      // Calculate the initial offset between camera and model (assuming model starts at origin)
      cameraOffset.current = camera.position.z - 0; // Model starts at z=0
    }
  }, [camera]);

  useEffect(() => {
    if (!actions[animation]) return;
    actions[animation].reset().fadeIn(0).play();
    return () => {
      if (actions[animation]) actions[animation].fadeOut(0);
    };
  }, [animation, actions]);

  useFrame((_, delta) => {
    if (!group.current) return;
    
    // Ensure animation speed is always normal
    if (actions && actions[animation]) {
      actions[animation].setEffectiveTimeScale(1);
    }
    
    // Handle automatic walking to target
    if (isAutoWalking && autoWalkTarget !== null) {
      const currentZ = group.current.position.z;
      const targetZ = autoWalkTarget;
      const distance = Math.abs(targetZ - currentZ);
      
      // Debug logging
      if (Math.random() < 0.1) { // Log every ~10th frame to avoid spam
        console.log(`Auto-walking: Current=${currentZ.toFixed(2)}, Target=${targetZ}, Distance=${distance.toFixed(2)}, Direction=${autoWalkDirection}`);
      }
      
      // Check if we've reached the target (smaller threshold for more precise stopping)
      if (distance < 0.3) {
        // Stop automatic walking
        console.log("Reached target! Stopping auto-walk");
        setIsAutoWalking(false);
        setAutoWalkTarget(null);
        setAutoWalkDirection(null);
        setAnimation("Idle");
        setRotationY(0); // Face forward when idle
        group.current.position.z = targetZ; // Snap to exact position
        return;
      }
      
      // Check if we've passed the target (more precise checking)
      if (autoWalkDirection === "forward" && currentZ >= targetZ) {
        console.log("Passed target while going forward! Stopping");
        setIsAutoWalking(false);
        setAutoWalkTarget(null);
        setAutoWalkDirection(null);
        setAnimation("Idle");
        setRotationY(0);
        group.current.position.z = targetZ;
        return;
      } else if (autoWalkDirection === "backward" && currentZ <= targetZ) {
        console.log("Passed target while going backward! Stopping");
        setIsAutoWalking(false);
        setAutoWalkTarget(null);
        setAutoWalkDirection(null);
        setAnimation("Idle");
        setRotationY(0);
        group.current.position.z = targetZ;
        return;
      }
    }
    
    // Move forward/backward based on animation and rotationY (both manual and auto movement)
    if (animation === "Walking") {
      const speed = 4;
      const forward = new THREE.Vector3(0, 0, 1);
      forward.applyAxisAngle(new THREE.Vector3(0, 1, 0), rotationY);
      forward.multiplyScalar(speed * delta);

      // Calculate next position
      const nextZ = group.current.position.z + forward.z;
      const nextX = group.current.position.x + forward.x;

      // Removed boundary checks - character can move anywhere
      group.current.position.add(forward);
    }
    
    // Reset root bone position to prevent animation snap/lag
    if (nodes.rp_nathan_animated_003_walking_root) {
      nodes.rp_nathan_animated_003_walking_root.position.set(0, 0, 0);
    }
    
    // Smooth camera follow logic with proper interpolation
    if (initialCameraPosition.current && group.current && cameraOffset.current !== null) {
      // Calculate target camera position based on model movement
      const modelPositionDelta = group.current.position.z - lastModelPosition.current.z;
      
      // Update target camera position to maintain constant offset
      targetCameraPosition.current.x = initialCameraPosition.current.x;
      targetCameraPosition.current.y = initialCameraPosition.current.y;
      // Maintain constant offset: camera should always be cameraOffset distance behind the model
      targetCameraPosition.current.z = group.current.position.z + cameraOffset.current;
      
      // Adjust lerp factor for smooth camera movement
      const lerpFactor = Math.min(1, 8 * delta); // Same speed for both mobile and desktop
      camera.position.lerp(targetCameraPosition.current, lerpFactor);
      
      // Console log camera position for debugging
      console.log('Camera Position:', {
        x: camera.position.x.toFixed(2),
        y: camera.position.y.toFixed(2),
        z: camera.position.z.toFixed(2)
      });
      
      // Update camera look-at target
      const lookAtTarget = new THREE.Vector3(
        group.current.position.x, 
        group.current.position.y + 1, 
        group.current.position.z
      );
      camera.lookAt(lookAtTarget);
      
      // Store current model position for next frame
      lastModelPosition.current.copy(group.current.position);
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="rp_nathan_animated_003_walking"
          rotation={[0, rotationY, 0]}
          scale={0.009}
        >
          <group name="rp_nathan_animated_003_walking_CTRL">
            <group name="Armature">
              <primitive object={nodes.rp_nathan_animated_003_walking_root} />
              <skinnedMesh name="rp_nathan_animated_003_walking_geo" geometry={nodes.rp_nathan_animated_003_walking_geo.geometry} material={materials.rp_nathan_animated_003_mat} skeleton={nodes.rp_nathan_animated_003_walking_geo.skeleton} />
            </group>
          </group>
          <group name="rp_nathan_animated_003_walking_geoGRP" />
        </group>
      </group>
    </group>
  )
}


useGLTF.preload('/model/untitled.glb')
useFBX.preload('/animation/idle.fbx')
useFBX.preload('/animation/Walking.fbx')
useFBX.preload('/animation/Standing React Death Right.fbx')
useFBX.preload('/animation/YourBoundaryAnim.fbx')
export default Model
