/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/board.glb -o C:\Users\91827\Desktop\portfolio\vite-project\src\assets\components\board.jsx -k -r public 
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-billboard-ca30a19b7026435684c50f334067cdb1
Title: Futuristic Billboard
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Board(props) {
  const { nodes, materials } = useGLTF('/model/board.glb')
  return (
    <group
      {...props}
      dispose={null}
      scale={1.2}
      position={[-4, 0, 29]}
    >
      <group name="Sketchfab_model" rotation={[1.521, 0, 0]}>
        <group name="baca7faba79f4775b05be1f3be5700fffbx" rotation={[-Math.PI, 0, Math.PI/8]} scale={0.005}>
          <group name="Lamp" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Lamp_Black_and_white_Metal_Plate_011__0" geometry={nodes.Lamp_Black_and_white_Metal_Plate_011__0.geometry} material={materials.Black_and_white_Metal_Plate_011} />
            <mesh name="Lamp_black_Metal_Gold_001_0" geometry={nodes.Lamp_black_Metal_Gold_001_0.geometry} material={materials.black_Metal_Gold_001} />
            <mesh name="Lamp_Lamp_0" geometry={nodes.Lamp_Lamp_0.geometry} material={materials.Lamp} />
          </group>
          <group name="Lamp005" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Lamp005_Black_and_white_Metal_Plate_011__0" geometry={nodes.Lamp005_Black_and_white_Metal_Plate_011__0.geometry} material={materials.Black_and_white_Metal_Plate_011} />
            <mesh name="Lamp005_black_Metal_Gold_001_0" geometry={nodes.Lamp005_black_Metal_Gold_001_0.geometry} material={materials.black_Metal_Gold_001} />
            <mesh name="Lamp005_Lamp_0" geometry={nodes.Lamp005_Lamp_0.geometry} material={materials.Lamp} />
          </group>
          <group name="Lamp010" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Lamp010_Black_and_white_Metal_Plate_011__0" geometry={nodes.Lamp010_Black_and_white_Metal_Plate_011__0.geometry} material={materials.Black_and_white_Metal_Plate_011} />
            <mesh name="Lamp010_black_Metal_Gold_001_0" geometry={nodes.Lamp010_black_Metal_Gold_001_0.geometry} material={materials.black_Metal_Gold_001} />
            <mesh name="Lamp010_Lamp_0" geometry={nodes.Lamp010_Lamp_0.geometry} material={materials.Lamp} />
          </group>
          <group name="Lamp015" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Lamp015_Black_and_white_Metal_Plate_011__0" geometry={nodes.Lamp015_Black_and_white_Metal_Plate_011__0.geometry} material={materials.Black_and_white_Metal_Plate_011} />
            <mesh name="Lamp015_black_Metal_Gold_001_0" geometry={nodes.Lamp015_black_Metal_Gold_001_0.geometry} material={materials.black_Metal_Gold_001} />
            <mesh name="Lamp015_Lamp_0" geometry={nodes.Lamp015_Lamp_0.geometry} material={materials.Lamp} />
          </group>
          <mesh name="Cube_black_Metal_Grill_004_Transparent_0" geometry={nodes.Cube_black_Metal_Grill_004_Transparent_0.geometry} material={materials.black_Metal_Grill_004_Transparent} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder_black_concrete_tles_holes_pbr___0" geometry={nodes.Cylinder_black_concrete_tles_holes_pbr___0.geometry} material={materials.black_concrete_tles_holes_pbr} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder002_black_concrete_tles_holes_pbr___0" geometry={nodes.Cylinder002_black_concrete_tles_holes_pbr___0.geometry} material={materials.black_concrete_tles_holes_pbr} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Empty001_Empty_0" geometry={nodes.Empty001_Empty_0.geometry} material={materials.Empty} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Empty002_Empty_0" geometry={nodes.Empty002_Empty_0.geometry} material={materials.Empty} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/board.glb')
