/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/butterfly.glb -o C:\Users\91827\Desktop\portfolio\vite-project\src\assets\components\Butterfly.jsx -k -r public 
Author: DragonJojo (https://sketchfab.com/DragonJojo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-glowing-butterfly-8fc026a9ee35463e96e38937a05a330b
Title: Blue glowing butterfly
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Butterfly(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/model/butterfly.glb')
  animations[0].name = "fly"
  const { actions } = useAnimations(animations, group)
 
  const [animation, setAnimation] = React.useState("Idle");
  console.log (animations)
  useEffect(() => {
    if (actions && actions.fly) {
      setAnimation("fly");
      actions.fly.reset().fadeIn(0).play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[2,  4, 35]} rotation={[Math.PI / 2, 0, 0]}>
          <group name="6cb9706577e44982a10dca33d66af2b7fbx" rotation={[-Math.PI, 0, 0]} scale={0.02}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="PB_Corps" position={[17.124, -500.963, -106.391]} rotation={[-0.216, 0.512, 1.877]}>
                  <group name="PB_AileD" rotation={[-1.222, 0, -1.396]}>
                    <group name="Object_8" position={[0.346, 0, -5.927]}>
                      <mesh name="PB_AileD_Papillon_bleu_0" geometry={nodes.PB_AileD_Papillon_bleu_0.geometry} material={materials.Papillon_bleu} />
                    </group>
                  </group>
                  <group name="PB_AileD001" rotation={[-1.222, 0, 1.396]}>
                    <mesh name="PB_AileD001_Papillon_bleu_0" geometry={nodes.PB_AileD001_Papillon_bleu_0.geometry} material={materials.Papillon_bleu} />
                  </group>
                  <group name="Object_5" position={[0, -3.543, -1.289]} rotation={[-1.222, 0, 0]}>
                    <mesh name="PB_Corps_Papillon_bleu_0" geometry={nodes.PB_Corps_Papillon_bleu_0.geometry} material={materials.Papillon_bleu} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/butterfly.glb')
