/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/untitled4.glb -o C:\Users\91827\Desktop\portfolio\vite-project\src\assets\components\Homemodel.jsx -k -r public 
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
 

export function Dragon(props) {
  const group = useRef()
  const { scene, animations: rawAnimations } = useGLTF('/model/untitled4.glb')
  const [shouldStartAnimation, setShouldStartAnimation] = useState(false)
 
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  console.log("Dragon animations available:", rawAnimations?.length || 0);
  console.log("Fly animation (index 7) exists:", !!rawAnimations?.[7]);
  
  const animations = React.useMemo(() => {
    if (!rawAnimations || rawAnimations.length === 0) {
      console.warn('No animations found in dragon model');
      return [];
    }
    
    const flyAnimation = rawAnimations[7];
    
    if (!flyAnimation) {
      console.warn('Fly animation (index 7) not found');
      return [];
    }
    
    // Only use fly animation for better performance
    flyAnimation.name = "fly2";
    return [flyAnimation];
  }, [rawAnimations]);

  const { actions } = useAnimations(animations, group)

  // Play fly2 animation on click
  // const handleClick = () => {
  //   if (actions.fly2) {
  //     actions.fly2.reset().fadeIn(0).play();
  //   }
  // };

  // Listen for welcome closed event to start fly animation immediately
  useEffect(() => {
    const handleWelcomeClosed = () => {
      console.log('Welcome closed, starting dragon fly animation immediately...');
      setShouldStartAnimation(true);
    };

    window.addEventListener('welcomeClosed', handleWelcomeClosed);
    return () => window.removeEventListener('welcomeClosed', handleWelcomeClosed);
  }, []);

  // Start fly animation when shouldStartAnimation becomes true
  useEffect(() => {
    if (shouldStartAnimation && actions.fly2) {
      console.log('Dragon starting to fly immediately!');
      actions.fly2.reset().play(0);
      actions.fly2.setLoop(2, 0); // Loop infinitely
    }
  }, [shouldStartAnimation, actions.fly2]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[3, 0, 2]}
      rotation={[0, -Math.PI/4, 0]}
      // onClick={handleClick}
    >
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
          <group name="M_B_44_Qishilong_skin_SkeletonFBX" rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="M_B_44_Qishilong_skin" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.MI_M_B_44_Qishilong_body02_Inst} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.MI_M_B_44_Qishilong_body02_2_Inst} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/untitled4.glb')

