/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\91827\OneDrive\Desktop\portfolio\vite-project\public\model\table.glb --output C:\Users\91827\OneDrive\Desktop\portfolio\vite-project\src\assets\components\Table.jsx 
Author: Brandon Baldwin (https://sketchfab.com/Fecalmancer)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/holo-table-2e97eadc6aed4d3f860e0cfccce52ffc
Title: Holo-Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Monitor } from './Monitor'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials } = useGLTF('/model/table.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[4, 0, 29]}>
      {/* Table Component */}
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
          <group name="Holo_Tablefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">

                <group name="Table" position={[0, 55.561, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={30.48}>
                  <mesh name="Table_Table_0" geometry={nodes.Table_Table_0.geometry} material={materials.Table} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      
      {/* Monitor positioned above the table */}
      <group position={[0, 1.12, 0]} scale={0.8}>
        <Monitor noPosition={true} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/table.glb')
// Export both the combined component and table-only component
export { Model as TableWithMonitor }
